pub use custom_name::CustomName;
pub use golden_simples::{GoldenSimples, GoldenSimplesPresets};
pub use transform::Transform;

use crate::internal::Serializable;
use anyhow::{anyhow, Error};
use enum_primitive_derive::Primitive;
use num_traits::ToPrimitive;
use serde::{Deserialize, Serialize};
use std::any::TypeId;

mod custom_name;
mod golden_simples;
mod transform;

// TODO: Handle components that have a name string instead of id and version.
#[derive(Debug, Clone, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Component {
    pub version: i32,
    pub guid: u32,

    #[serde(flatten)]
    pub data: ComponentData,
}

impl Component {
    pub fn id(&self) -> ComponentId {
        self.data.id()
    }

    #[rustfmt::skip]
    pub(crate) fn from_builder(
        component_id: ComponentId,
        mut builder: impl ComponentBuilder,
    ) -> Result<Self, Error> {
        let unserializable = || Err(anyhow!("{:?} in not a serializable component", component_id));

        match component_id {
            ComponentId::Invalid_ => unserializable(),
            ComponentId::None => unserializable(),
            ComponentId::Transform => builder.implemented(ComponentData::Transform, Transform::VERSION),
            ComponentId::GoldenSimples => builder.implemented(ComponentData::GoldenSimples, GoldenSimples::VERSION),
            ComponentId::MeshRenderer => builder.raw(ComponentData::MeshRenderer),
            ComponentId::MeshFilter => unserializable(),
            ComponentId::SkinnedMeshRenderer => unserializable(),
            ComponentId::LineRenderer => unserializable(),
            ComponentId::TrailRenderer => unserializable(),
            ComponentId::TextMesh => builder.raw(ComponentData::TextMesh),
            ComponentId::Animation => unserializable(),
            ComponentId::Light => builder.raw(ComponentData::Light),
            ComponentId::LensFlare => builder.raw(ComponentData::LensFlare),
            ComponentId::ParticleSystem => unserializable(),
            ComponentId::Projector => builder.raw(ComponentData::Projector),
            ComponentId::MeshCollider => unserializable(),
            ComponentId::SphereCollider => builder.raw(ComponentData::SphereCollider),
            ComponentId::BoxCollider => builder.raw(ComponentData::BoxCollider),
            ComponentId::CapsuleCollider => builder.raw(ComponentData::CapsuleCollider),
            ComponentId::Rigidbody => unserializable(),
            ComponentId::AudioSource => unserializable(),
            ComponentId::ConstantForce => unserializable(),
            ComponentId::BezierSplineTrack => builder.raw(ComponentData::BezierSplineTrack),
            ComponentId::TrackSegment => builder.raw(ComponentData::TrackSegment),
            ComponentId::TrackLink => builder.raw(ComponentData::TrackLink),
            ComponentId::RigidbodyAxisRotationLogic => builder.raw(ComponentData::RigidbodyAxisRotationLogic),
            ComponentId::BackAndForthSawLogic => builder.raw(ComponentData::BackAndForthSawLogic),
            ComponentId::CheckpointLogic => builder.raw(ComponentData::CheckpointLogic),
            ComponentId::LaserLogic => unserializable(),
            ComponentId::LightFlickerLogic => builder.raw(ComponentData::LightFlickerLogic),
            ComponentId::SceneryCameraLogic => unserializable(),
            ComponentId::Group => builder.raw(ComponentData::Group),
            ComponentId::SkyboxAdder => unserializable(),
            ComponentId::LevelCubeMapRenderer => unserializable(),
            ComponentId::LevelGodRayCaster => unserializable(),
            ComponentId::TutorialBoxText => builder.raw(ComponentData::TutorialBoxText),
            ComponentId::BoostPadLogic => unserializable(),
            ComponentId::CloudCreator => unserializable(),
            ComponentId::FlyingRingLogic => builder.raw(ComponentData::FlyingRingLogic),
            ComponentId::PopupBlockerLogic => builder.raw(ComponentData::PopupBlockerLogic),
            ComponentId::PulseLight => builder.raw(ComponentData::PulseLight),
            ComponentId::PulseMaterial => builder.raw(ComponentData::PulseMaterial),
            ComponentId::SmoothRandomPosition => builder.raw(ComponentData::SmoothRandomPosition),
            ComponentId::SoccerGoalLogic => builder.raw(ComponentData::SoccerGoalLogic),
            ComponentId::VirusMineLogic => builder.raw(ComponentData::VirusMineLogic),
            ComponentId::AnimateUVs => unserializable(),
            ComponentId::BrightenCarHeadlights => builder.raw(ComponentData::BrightenCarHeadlights),
            ComponentId::TrackManipulationNode => unserializable(),
            ComponentId::SpawnLaserLogic => unserializable(),
            ComponentId::GameData => builder.raw(ComponentData::GameData),
            ComponentId::GraphicsSettings => builder.raw(ComponentData::GraphicsSettings),
            ComponentId::AudioSettings => builder.raw(ComponentData::AudioSettings),
            ComponentId::ControlsSettings => builder.raw(ComponentData::ControlsSettings),
            ComponentId::Profile => builder.raw(ComponentData::Profile),
            ComponentId::LevelSet => unserializable(),
            ComponentId::ToolInputCombos => builder.raw(ComponentData::ToolInputCombos),
            ComponentId::ColorPreset => builder.raw(ComponentData::ColorPreset),
            ComponentId::LocalLeaderboard => builder.raw(ComponentData::LocalLeaderboard),
            ComponentId::AxisRotationLogic => builder.raw(ComponentData::AxisRotationLogic),
            ComponentId::ParticleEmitLogic => builder.raw(ComponentData::ParticleEmitLogic),
            ComponentId::VirusSpiritSpawner => builder.raw(ComponentData::VirusSpiritSpawner),
            ComponentId::GlitchTrigger => unserializable(),
            ComponentId::Teleporter => unserializable(),
            ComponentId::PulseRotateOnTrigger => builder.raw(ComponentData::PulseRotateOnTrigger),
            ComponentId::TeleporterEntrance => builder.raw(ComponentData::TeleporterEntrance),
            ComponentId::TeleporterExit => builder.raw(ComponentData::TeleporterExit),
            ComponentId::ControlScheme => builder.raw(ComponentData::ControlScheme),
            ComponentId::DeviceToSchemeLinks => builder.raw(ComponentData::DeviceToSchemeLinks),
            ComponentId::ObjectSpawnCircle => builder.raw(ComponentData::ObjectSpawnCircle),
            ComponentId::InterpolateToPositionOnTrigger => builder.raw(ComponentData::InterpolateToPositionOnTrigger),
            ComponentId::EngageBrokenPieces => builder.raw(ComponentData::EngageBrokenPieces),
            ComponentId::GravityToggle => builder.raw(ComponentData::GravityToggle),
            ComponentId::CarSpawner => builder.raw(ComponentData::CarSpawner),
            ComponentId::RaceStartCarSpawner => builder.raw(ComponentData::RaceStartCarSpawner),
            ComponentId::LevelEditorCarSpawner => builder.raw(ComponentData::LevelEditorCarSpawner),
            ComponentId::OnlyActiveInLevelEditor => unserializable(),
            ComponentId::InfoDisplayLogic => builder.raw(ComponentData::InfoDisplayLogic),
            ComponentId::MusicTrigger => builder.raw(ComponentData::MusicTrigger),
            ComponentId::TabPopulator => builder.raw(ComponentData::TabPopulator),
            ComponentId::AdventureAbilitySettings => builder.raw(ComponentData::AdventureAbilitySettings),
            ComponentId::IndicatorDisplayLogic => builder.raw(ComponentData::IndicatorDisplayLogic),
            ComponentId::PulseCoreLogic => builder.raw(ComponentData::PulseCoreLogic),
            ComponentId::PulseAll => builder.raw(ComponentData::PulseAll),
            ComponentId::TeleporterExitCheckpoint => builder.raw(ComponentData::TeleporterExitCheckpoint),
            ComponentId::LevelSettings => builder.raw(ComponentData::LevelSettings),
            ComponentId::WingCorruptionZone => builder.raw(ComponentData::WingCorruptionZone),
            ComponentId::GenerateCreditsNames => builder.raw(ComponentData::GenerateCreditsNames),
            ComponentId::IntroCutsceneLightFadeIn => builder.raw(ComponentData::IntroCutsceneLightFadeIn),
            ComponentId::QuarantineTrigger => builder.raw(ComponentData::QuarantineTrigger),
            ComponentId::CarScreenTextDecodeTrigger => builder.raw(ComponentData::CarScreenTextDecodeTrigger),
            ComponentId::GlitchFieldLogic => builder.raw(ComponentData::GlitchFieldLogic),
            ComponentId::FogSkyboxAmbientChangeTrigger => builder.raw(ComponentData::FogSkyboxAmbientChangeTrigger),
            ComponentId::FinalCountdownLogic => builder.raw(ComponentData::FinalCountdownLogic),
            ComponentId::SetActiveOnIntroCutsceneStarted => builder.raw(ComponentData::SetActiveOnIntroCutsceneStarted),
            ComponentId::SphericalGravityTrigger => unserializable(),
            ComponentId::RaceEndLogic => builder.raw(ComponentData::RaceEndLogic),
            ComponentId::EnableAbilitiesTrigger => builder.raw(ComponentData::EnableAbilitiesTrigger),
            ComponentId::SphericalGravity => builder.raw(ComponentData::SphericalGravity),
            ComponentId::GlobalFogLogic => unserializable(),
            ComponentId::CreditsNameOrbLogic => builder.raw(ComponentData::CreditsNameOrbLogic),
            ComponentId::DisableLocalCarWarnings => builder.raw(ComponentData::DisableLocalCarWarnings),
            ComponentId::CustomName => builder.implemented(ComponentData::CustomName, CustomName::VERSION),
            ComponentId::SplineSegment => builder.raw(ComponentData::SplineSegment),
            ComponentId::WarningPulseLight => builder.raw(ComponentData::WarningPulseLight),
            ComponentId::RumbleZone => builder.raw(ComponentData::RumbleZone),
            ComponentId::HideOnVirusSpiritEvent => builder.raw(ComponentData::HideOnVirusSpiritEvent),
            ComponentId::TrackAttachment => builder.raw(ComponentData::TrackAttachment),
            ComponentId::LevelPlaylist => builder.raw(ComponentData::LevelPlaylist),
            ComponentId::ProfileProgress => builder.raw(ComponentData::ProfileProgress),
            ComponentId::GeneralSettings => builder.raw(ComponentData::GeneralSettings),
            ComponentId::ReplayAllPurposeTrigger => unserializable(),
            ComponentId::WorkshopPublishedFileInfos => builder.raw(ComponentData::WorkshopPublishedFileInfos),
            ComponentId::WarpAnchor => builder.raw(ComponentData::WarpAnchor),
            ComponentId::SetActiveOnMIDIEvent => builder.raw(ComponentData::SetActiveOnMIDIEvent),
            ComponentId::TurnLightOnNearCar => builder.raw(ComponentData::TurnLightOnNearCar),
            ComponentId::Traffic => builder.raw(ComponentData::Traffic),
            ComponentId::TrackManipulatorNode => builder.raw(ComponentData::TrackManipulatorNode),
            ComponentId::TurnLightOnNearCarTrigger => unserializable(),
            ComponentId::AudioEventTrigger => builder.raw(ComponentData::AudioEventTrigger),
            ComponentId::LevelEditorSettings => builder.raw(ComponentData::LevelEditorSettings),
            ComponentId::EmpireProximityDoorLogic => builder.raw(ComponentData::EmpireProximityDoorLogic),
            ComponentId::Biodome => builder.raw(ComponentData::Biodome),
            ComponentId::TunnelHorrorLogic => builder.raw(ComponentData::TunnelHorrorLogic),
            ComponentId::LogicTrigger => unserializable(),
            ComponentId::ChangeEmissiveColorLogicTriggerListener => unserializable(),
            ComponentId::MoveLogicTriggerListener => unserializable(),
            ComponentId::RotateLogicTriggerListener => unserializable(),
            ComponentId::ScaleLogicTriggerListener => unserializable(),
            ComponentId::VirusSpiritWarpTeaserLogic => builder.raw(ComponentData::VirusSpiritWarpTeaserLogic),
            ComponentId::CarReplayData => builder.raw(ComponentData::CarReplayData),
            ComponentId::LevelImageCamera => builder.raw(ComponentData::LevelImageCamera),
            ComponentId::ParticlesGPU => builder.raw(ComponentData::ParticlesGPU),
            ComponentId::KillGridBox => builder.raw(ComponentData::KillGridBox),
            ComponentId::SetActiveAfterWarp => builder.raw(ComponentData::SetActiveAfterWarp),
            ComponentId::AmbientAudioObject => builder.raw(ComponentData::AmbientAudioObject),
            ComponentId::BiodomeAudioInterpolator => builder.raw(ComponentData::BiodomeAudioInterpolator),
            ComponentId::MoveElectricityAlongWire => builder.raw(ComponentData::MoveElectricityAlongWire),
            ComponentId::ActivationRampLogic => builder.raw(ComponentData::ActivationRampLogic),
            ComponentId::ZEventTrigger => builder.raw(ComponentData::ZEventTrigger),
            ComponentId::ZEventListener => builder.raw(ComponentData::ZEventListener),
            ComponentId::BlackPortalLogic => builder.raw(ComponentData::BlackPortalLogic),
            ComponentId::VRSettings => builder.raw(ComponentData::VRSettings),
            ComponentId::CutsceneCamera => builder.raw(ComponentData::CutsceneCamera),
            ComponentId::ProfileStats => builder.raw(ComponentData::ProfileStats),
            ComponentId::InterpolateToRotationOnTrigger => builder.raw(ComponentData::InterpolateToRotationOnTrigger),
            ComponentId::MoveAlongAttachedTrack => builder.raw(ComponentData::MoveAlongAttachedTrack),
            ComponentId::ShowDuringGlitch => builder.raw(ComponentData::ShowDuringGlitch),
            ComponentId::AddCameraNoise => builder.raw(ComponentData::AddCameraNoise),
            ComponentId::CarVoiceTrigger => builder.raw(ComponentData::CarVoiceTrigger),
            ComponentId::HoverScreenSpecialObjectTrigger => builder.raw(ComponentData::HoverScreenSpecialObjectTrigger),
            ComponentId::ReplaySettings => builder.raw(ComponentData::ReplaySettings),
            ComponentId::CutsceneCamForTrailer => builder.raw(ComponentData::CutsceneCamForTrailer),
            ComponentId::LevelInfos => builder.raw(ComponentData::LevelInfos),
            ComponentId::AchievementTrigger => builder.raw(ComponentData::AchievementTrigger),
            ComponentId::ArenaCarSpawner => builder.raw(ComponentData::ArenaCarSpawner),
            ComponentId::Animated => builder.raw(ComponentData::Animated),
            ComponentId::BlinkInTrigger => builder.raw(ComponentData::BlinkInTrigger),
            ComponentId::CarScreenImageTrigger => builder.raw(ComponentData::CarScreenImageTrigger),
            ComponentId::ExcludeFromEMP => builder.raw(ComponentData::ExcludeFromEMP),
            ComponentId::InfiniteCooldownTrigger => builder.raw(ComponentData::InfiniteCooldownTrigger),
            ComponentId::DiscoverableStuntArea => builder.raw(ComponentData::DiscoverableStuntArea),
            ComponentId::ForceVolume => builder.raw(ComponentData::ForceVolume),
            ComponentId::AdventureModeCompleteTrigger => builder.raw(ComponentData::AdventureModeCompleteTrigger),
            ComponentId::CountdownTextMeshLogic => builder.raw(ComponentData::CountdownTextMeshLogic),
            ComponentId::AbilitySignButtonColorLogic => builder.raw(ComponentData::AbilitySignButtonColorLogic),
            ComponentId::GoldenAnimator => builder.raw(ComponentData::GoldenAnimator),
            ComponentId::StuntCollectibleSpawner => unserializable(),
            ComponentId::AnimatorAudio => builder.raw(ComponentData::AnimatorAudio),
            ComponentId::AnimatorCameraShake => builder.raw(ComponentData::AnimatorCameraShake),
            ComponentId::ShardCluster => builder.raw(ComponentData::ShardCluster),
            ComponentId::AdventureSpecialIntro => builder.raw(ComponentData::AdventureSpecialIntro),
            ComponentId::AudioEffectZone => builder.raw(ComponentData::AudioEffectZone),
            ComponentId::CinematicCamera => builder.raw(ComponentData::CinematicCamera),
            ComponentId::CinematicCameraFocalPoint => builder.raw(ComponentData::CinematicCameraFocalPoint),
            ComponentId::SetAbilitiesTrigger => builder.raw(ComponentData::SetAbilitiesTrigger),
            ComponentId::LostToEchoesIntroCutscene => builder.raw(ComponentData::LostToEchoesIntroCutscene),
            ComponentId::CutsceneText => builder.raw(ComponentData::CutsceneText),
            ComponentId::UltraPlanet => builder.raw(ComponentData::UltraPlanet),
            ComponentId::DeadCarLogic => builder.raw(ComponentData::DeadCarLogic),
            ComponentId::RollingBarrelDropperLogic => builder.raw(ComponentData::RollingBarrelDropperLogic),
            ComponentId::AdventureFinishTrigger => builder.raw(ComponentData::AdventureFinishTrigger),
            ComponentId::AchievementSettings => builder.raw(ComponentData::AchievementSettings),
            ComponentId::InterpolateRTPCLogic => builder.raw(ComponentData::InterpolateRTPCLogic),
            ComponentId::TriggerCooldownLogic => builder.raw(ComponentData::TriggerCooldownLogic),
            ComponentId::ShadowsChangedListener => builder.raw(ComponentData::ShadowsChangedListener),
            ComponentId::LookAtCamera => builder.raw(ComponentData::LookAtCamera),
            ComponentId::InterceptorCollectable => unserializable(),
            ComponentId::CubeMapRenderer => builder.raw(ComponentData::CubeMapRenderer),
            ComponentId::RealtimeReflectionRenderer => builder.raw(ComponentData::RealtimeReflectionRenderer),
            ComponentId::VirusDropperDroneLogic => builder.raw(ComponentData::VirusDropperDroneLogic),
            ComponentId::OnCollisionBreakApartLogic => builder.raw(ComponentData::OnCollisionBreakApartLogic),
            ComponentId::CheatSettings => builder.raw(ComponentData::CheatSettings),
            ComponentId::IgnoreInCullGroups => builder.raw(ComponentData::IgnoreInCullGroups),
            ComponentId::IgnoreInputTrigger => builder.raw(ComponentData::IgnoreInputTrigger),
            ComponentId::PowerPosterLogic => builder.raw(ComponentData::PowerPosterLogic),
            ComponentId::MusicZone => builder.raw(ComponentData::MusicZone),
            ComponentId::LightsFlickerLogic => builder.raw(ComponentData::LightsFlickerLogic),
            ComponentId::CutsceneManagerLogic => builder.raw(ComponentData::CutsceneManagerLogic),
            ComponentId::FadeOut => builder.raw(ComponentData::FadeOut),
            ComponentId::Flock => builder.raw(ComponentData::Flock),
            ComponentId::GPSTrigger => builder.raw(ComponentData::GPSTrigger),
            ComponentId::ResetOnCarDeath => unserializable(),
            ComponentId::SprintMode => builder.raw(ComponentData::SprintMode),
            ComponentId::StuntMode => builder.raw(ComponentData::StuntMode),
            ComponentId::SoccerMode => builder.raw(ComponentData::SoccerMode),
            ComponentId::FreeRoamMode => builder.raw(ComponentData::FreeRoamMode),
            ComponentId::ReverseTagMode => builder.raw(ComponentData::ReverseTagMode),
            ComponentId::LevelEditorPlayMode => builder.raw(ComponentData::LevelEditorPlayMode),
            ComponentId::CoopSprintMode => builder.raw(ComponentData::CoopSprintMode),
            ComponentId::ChallengeMode => builder.raw(ComponentData::ChallengeMode),
            ComponentId::AdventureMode => builder.raw(ComponentData::AdventureMode),
            ComponentId::SpeedAndStyleMode => builder.raw(ComponentData::SpeedAndStyleMode),
            ComponentId::TrackmogrifyMode => builder.raw(ComponentData::TrackmogrifyMode),
            ComponentId::DemoMode => builder.raw(ComponentData::DemoMode),
            ComponentId::MainMenuMode => builder.raw(ComponentData::MainMenuMode),
            ComponentId::LostToEchoesMode => builder.raw(ComponentData::LostToEchoesMode),
            ComponentId::NexusMode => builder.raw(ComponentData::NexusMode),
            ComponentId::TheOtherSideMode => builder.raw(ComponentData::TheOtherSideMode),
        }
    }
}

#[allow(clippy::upper_case_acronyms)]
#[repr(i16)]
#[derive(
    Debug, Copy, Clone, Hash, Eq, PartialEq, Ord, PartialOrd, Primitive, Serialize, Deserialize,
)]
pub enum ComponentId {
    Invalid_ = -1_i16,
    None = 0,
    Transform = 1,
    MeshFilter = 2,
    MeshRenderer = 3,
    SkinnedMeshRenderer = 4,
    LineRenderer = 5,
    TrailRenderer = 6,
    TextMesh = 7,
    Animation = 8,
    Light = 9,
    LensFlare = 10,
    ParticleSystem = 11,
    Projector = 12,
    MeshCollider = 13,
    SphereCollider = 14,
    BoxCollider = 15,
    CapsuleCollider = 16,
    Rigidbody = 17,
    AudioSource = 18,
    ConstantForce = 19,
    BezierSplineTrack = 20,
    TrackSegment = 21,
    TrackLink = 22,
    RigidbodyAxisRotationLogic = 23,
    BackAndForthSawLogic = 24,
    CheckpointLogic = 25,
    LaserLogic = 26,
    LightFlickerLogic = 27,
    SceneryCameraLogic = 28,
    Group = 29,
    SkyboxAdder = 30,
    LevelCubeMapRenderer = 31,
    LevelGodRayCaster = 32,
    TutorialBoxText = 33,
    BoostPadLogic = 34,
    CloudCreator = 35,
    FlyingRingLogic = 36,
    PopupBlockerLogic = 37,
    PulseLight = 38,
    PulseMaterial = 39,
    SmoothRandomPosition = 40,
    SoccerGoalLogic = 41,
    VirusMineLogic = 42,
    AnimateUVs = 43,
    BrightenCarHeadlights = 44,
    TrackManipulationNode = 45,
    SpawnLaserLogic = 46,
    GameData = 47,
    GraphicsSettings = 48,
    AudioSettings = 49,
    ControlsSettings = 50,
    Profile = 51,
    LevelSet = 52,
    ToolInputCombos = 53,
    ColorPreset = 54,
    LocalLeaderboard = 55,
    AxisRotationLogic = 56,
    ParticleEmitLogic = 57,
    VirusSpiritSpawner = 58,
    GlitchTrigger = 59,
    Teleporter = 60,
    PulseRotateOnTrigger = 61,
    TeleporterEntrance = 62,
    TeleporterExit = 63,
    ControlScheme = 64,
    DeviceToSchemeLinks = 65,
    ObjectSpawnCircle = 66,
    InterpolateToPositionOnTrigger = 67,
    EngageBrokenPieces = 68,
    GravityToggle = 69,
    CarSpawner = 70,
    RaceStartCarSpawner = 71,
    LevelEditorCarSpawner = 72,
    OnlyActiveInLevelEditor = 73,
    InfoDisplayLogic = 74,
    MusicTrigger = 75,
    TabPopulator = 76,
    AdventureAbilitySettings = 77,
    IndicatorDisplayLogic = 78,
    PulseCoreLogic = 79,
    PulseAll = 80,
    TeleporterExitCheckpoint = 81,
    LevelSettings = 82,
    WingCorruptionZone = 83,
    GenerateCreditsNames = 84,
    IntroCutsceneLightFadeIn = 85,
    QuarantineTrigger = 86,
    CarScreenTextDecodeTrigger = 87,
    GlitchFieldLogic = 88,
    FogSkyboxAmbientChangeTrigger = 89,
    FinalCountdownLogic = 90,
    SetActiveOnIntroCutsceneStarted = 91,
    SphericalGravityTrigger = 92,
    RaceEndLogic = 93,
    EnableAbilitiesTrigger = 94,
    SphericalGravity = 95,
    GlobalFogLogic = 96,
    CreditsNameOrbLogic = 97,
    DisableLocalCarWarnings = 98,
    CustomName = 99,
    SplineSegment = 100,
    WarningPulseLight = 101,
    RumbleZone = 102,
    HideOnVirusSpiritEvent = 103,
    TrackAttachment = 104,
    LevelPlaylist = 105,
    ProfileProgress = 106,
    GeneralSettings = 107,
    ReplayAllPurposeTrigger = 108,
    WorkshopPublishedFileInfos = 109,
    WarpAnchor = 110,
    SetActiveOnMIDIEvent = 111,
    TurnLightOnNearCar = 112,
    Traffic = 113,
    TrackManipulatorNode = 114,
    TurnLightOnNearCarTrigger = 115,
    AudioEventTrigger = 116,
    LevelEditorSettings = 117,
    EmpireProximityDoorLogic = 118,
    Biodome = 119,
    TunnelHorrorLogic = 120,
    LogicTrigger = 121,
    ChangeEmissiveColorLogicTriggerListener = 122,
    MoveLogicTriggerListener = 123,
    RotateLogicTriggerListener = 124,
    ScaleLogicTriggerListener = 125,
    VirusSpiritWarpTeaserLogic = 126,
    CarReplayData = 127,
    LevelImageCamera = 128,
    ParticlesGPU = 129,
    KillGridBox = 130,
    GoldenSimples = 131,
    SetActiveAfterWarp = 132,
    AmbientAudioObject = 133,
    BiodomeAudioInterpolator = 134,
    MoveElectricityAlongWire = 135,
    ActivationRampLogic = 136,
    ZEventTrigger = 137,
    ZEventListener = 138,
    BlackPortalLogic = 139,
    VRSettings = 140,
    CutsceneCamera = 141,
    ProfileStats = 142,
    InterpolateToRotationOnTrigger = 143,
    MoveAlongAttachedTrack = 144,
    ShowDuringGlitch = 145,
    AddCameraNoise = 146,
    CarVoiceTrigger = 147,
    HoverScreenSpecialObjectTrigger = 148,
    ReplaySettings = 149,
    CutsceneCamForTrailer = 150,
    LevelInfos = 151,
    AchievementTrigger = 152,
    ArenaCarSpawner = 153,
    Animated = 154,
    BlinkInTrigger = 155,
    CarScreenImageTrigger = 156,
    ExcludeFromEMP = 157,
    InfiniteCooldownTrigger = 158,
    DiscoverableStuntArea = 159,
    ForceVolume = 160,
    AdventureModeCompleteTrigger = 161,
    CountdownTextMeshLogic = 162,
    AbilitySignButtonColorLogic = 163,
    GoldenAnimator = 164,
    StuntCollectibleSpawner = 165,
    AnimatorAudio = 166,
    AnimatorCameraShake = 167,
    ShardCluster = 168,
    AdventureSpecialIntro = 169,
    AudioEffectZone = 170,
    CinematicCamera = 171,
    CinematicCameraFocalPoint = 172,
    SetAbilitiesTrigger = 173,
    LostToEchoesIntroCutscene = 174,
    CutsceneText = 175,
    UltraPlanet = 176,
    DeadCarLogic = 177,
    RollingBarrelDropperLogic = 178,
    AdventureFinishTrigger = 179,
    AchievementSettings = 180,
    InterpolateRTPCLogic = 181,
    TriggerCooldownLogic = 182,
    ShadowsChangedListener = 183,
    LookAtCamera = 184,
    InterceptorCollectable = 185,
    CubeMapRenderer = 186,
    RealtimeReflectionRenderer = 187,
    VirusDropperDroneLogic = 188,
    OnCollisionBreakApartLogic = 189,
    CheatSettings = 190,
    IgnoreInCullGroups = 191,
    IgnoreInputTrigger = 192,
    PowerPosterLogic = 193,
    MusicZone = 194,
    LightsFlickerLogic = 195,
    CutsceneManagerLogic = 196,
    FadeOut = 197,
    Flock = 198,
    GPSTrigger = 199,
    ResetOnCarDeath = 200,
    SprintMode = 201,
    StuntMode = 202,
    SoccerMode = 203,
    FreeRoamMode = 204,
    ReverseTagMode = 205,
    LevelEditorPlayMode = 206,
    CoopSprintMode = 207,
    ChallengeMode = 208,
    AdventureMode = 209,
    SpeedAndStyleMode = 210,
    TrackmogrifyMode = 211,
    DemoMode = 212,
    MainMenuMode = 213,
    LostToEchoesMode = 214,
    NexusMode = 215,
    TheOtherSideMode = 216,
}

#[rustfmt::skip]
impl ComponentId {
    pub fn is_implemented(&self) -> bool {
        fn check_variant<T: 'static, U>(_: fn(T) -> U) -> bool {
            TypeId::of::<T>() != TypeId::of::<RawComponentData>()
        }

        match self {
            ComponentId::Invalid_ => false,
            ComponentId::None => false,
            ComponentId::Transform => check_variant(ComponentData::Transform),
            ComponentId::MeshFilter => false,
            ComponentId::MeshRenderer => check_variant(ComponentData::MeshRenderer),
            ComponentId::SkinnedMeshRenderer => false,
            ComponentId::LineRenderer => false,
            ComponentId::TrailRenderer => false,
            ComponentId::TextMesh => check_variant(ComponentData::TextMesh),
            ComponentId::Animation => false,
            ComponentId::Light => check_variant(ComponentData::Light),
            ComponentId::LensFlare => check_variant(ComponentData::LensFlare),
            ComponentId::ParticleSystem => false,
            ComponentId::Projector => check_variant(ComponentData::Projector),
            ComponentId::MeshCollider => false,
            ComponentId::SphereCollider => check_variant(ComponentData::SphereCollider),
            ComponentId::BoxCollider => check_variant(ComponentData::BoxCollider),
            ComponentId::CapsuleCollider => check_variant(ComponentData::CapsuleCollider),
            ComponentId::Rigidbody => false,
            ComponentId::AudioSource => false,
            ComponentId::ConstantForce => false,
            ComponentId::BezierSplineTrack => check_variant(ComponentData::BezierSplineTrack),
            ComponentId::TrackSegment => check_variant(ComponentData::TrackSegment),
            ComponentId::TrackLink => check_variant(ComponentData::TrackLink),
            ComponentId::RigidbodyAxisRotationLogic => check_variant(ComponentData::RigidbodyAxisRotationLogic),
            ComponentId::BackAndForthSawLogic => check_variant(ComponentData::BackAndForthSawLogic),
            ComponentId::CheckpointLogic => check_variant(ComponentData::CheckpointLogic),
            ComponentId::LaserLogic => false,
            ComponentId::LightFlickerLogic => check_variant(ComponentData::LightFlickerLogic),
            ComponentId::SceneryCameraLogic => false,
            ComponentId::Group => check_variant(ComponentData::Group),
            ComponentId::SkyboxAdder => false,
            ComponentId::LevelCubeMapRenderer => false,
            ComponentId::LevelGodRayCaster => false,
            ComponentId::TutorialBoxText => check_variant(ComponentData::TutorialBoxText),
            ComponentId::BoostPadLogic => false,
            ComponentId::CloudCreator => false,
            ComponentId::FlyingRingLogic => check_variant(ComponentData::FlyingRingLogic),
            ComponentId::PopupBlockerLogic => check_variant(ComponentData::PopupBlockerLogic),
            ComponentId::PulseLight => check_variant(ComponentData::PulseLight),
            ComponentId::PulseMaterial => check_variant(ComponentData::PulseMaterial),
            ComponentId::SmoothRandomPosition => check_variant(ComponentData::SmoothRandomPosition),
            ComponentId::SoccerGoalLogic => check_variant(ComponentData::SoccerGoalLogic),
            ComponentId::VirusMineLogic => check_variant(ComponentData::VirusMineLogic),
            ComponentId::AnimateUVs => false,
            ComponentId::BrightenCarHeadlights => check_variant(ComponentData::BrightenCarHeadlights),
            ComponentId::TrackManipulationNode => false,
            ComponentId::SpawnLaserLogic => false,
            ComponentId::GameData => check_variant(ComponentData::GameData),
            ComponentId::GraphicsSettings => check_variant(ComponentData::GraphicsSettings),
            ComponentId::AudioSettings => check_variant(ComponentData::AudioSettings),
            ComponentId::ControlsSettings => check_variant(ComponentData::ControlsSettings),
            ComponentId::Profile => check_variant(ComponentData::Profile),
            ComponentId::LevelSet => false,
            ComponentId::ToolInputCombos => check_variant(ComponentData::ToolInputCombos),
            ComponentId::ColorPreset => check_variant(ComponentData::ColorPreset),
            ComponentId::LocalLeaderboard => check_variant(ComponentData::LocalLeaderboard),
            ComponentId::AxisRotationLogic => check_variant(ComponentData::AxisRotationLogic),
            ComponentId::ParticleEmitLogic => check_variant(ComponentData::ParticleEmitLogic),
            ComponentId::VirusSpiritSpawner => check_variant(ComponentData::VirusSpiritSpawner),
            ComponentId::GlitchTrigger => false,
            ComponentId::Teleporter => false,
            ComponentId::PulseRotateOnTrigger => check_variant(ComponentData::PulseRotateOnTrigger),
            ComponentId::TeleporterEntrance => check_variant(ComponentData::TeleporterEntrance),
            ComponentId::TeleporterExit => check_variant(ComponentData::TeleporterExit),
            ComponentId::ControlScheme => check_variant(ComponentData::ControlScheme),
            ComponentId::DeviceToSchemeLinks => check_variant(ComponentData::DeviceToSchemeLinks),
            ComponentId::ObjectSpawnCircle => check_variant(ComponentData::ObjectSpawnCircle),
            ComponentId::InterpolateToPositionOnTrigger => check_variant(ComponentData::InterpolateToPositionOnTrigger),
            ComponentId::EngageBrokenPieces => check_variant(ComponentData::EngageBrokenPieces),
            ComponentId::GravityToggle => check_variant(ComponentData::GravityToggle),
            ComponentId::CarSpawner => check_variant(ComponentData::CarSpawner),
            ComponentId::RaceStartCarSpawner => check_variant(ComponentData::RaceStartCarSpawner),
            ComponentId::LevelEditorCarSpawner => check_variant(ComponentData::LevelEditorCarSpawner),
            ComponentId::OnlyActiveInLevelEditor => false,
            ComponentId::InfoDisplayLogic => check_variant(ComponentData::InfoDisplayLogic),
            ComponentId::MusicTrigger => check_variant(ComponentData::MusicTrigger),
            ComponentId::TabPopulator => check_variant(ComponentData::TabPopulator),
            ComponentId::AdventureAbilitySettings => check_variant(ComponentData::AdventureAbilitySettings),
            ComponentId::IndicatorDisplayLogic => check_variant(ComponentData::IndicatorDisplayLogic),
            ComponentId::PulseCoreLogic => check_variant(ComponentData::PulseCoreLogic),
            ComponentId::PulseAll => check_variant(ComponentData::PulseAll),
            ComponentId::TeleporterExitCheckpoint => check_variant(ComponentData::TeleporterExitCheckpoint),
            ComponentId::LevelSettings => check_variant(ComponentData::LevelSettings),
            ComponentId::WingCorruptionZone => check_variant(ComponentData::WingCorruptionZone),
            ComponentId::GenerateCreditsNames => check_variant(ComponentData::GenerateCreditsNames),
            ComponentId::IntroCutsceneLightFadeIn => check_variant(ComponentData::IntroCutsceneLightFadeIn),
            ComponentId::QuarantineTrigger => check_variant(ComponentData::QuarantineTrigger),
            ComponentId::CarScreenTextDecodeTrigger => check_variant(ComponentData::CarScreenTextDecodeTrigger),
            ComponentId::GlitchFieldLogic => check_variant(ComponentData::GlitchFieldLogic),
            ComponentId::FogSkyboxAmbientChangeTrigger => check_variant(ComponentData::FogSkyboxAmbientChangeTrigger),
            ComponentId::FinalCountdownLogic => check_variant(ComponentData::FinalCountdownLogic),
            ComponentId::SetActiveOnIntroCutsceneStarted => check_variant(ComponentData::SetActiveOnIntroCutsceneStarted),
            ComponentId::SphericalGravityTrigger => false,
            ComponentId::RaceEndLogic => check_variant(ComponentData::RaceEndLogic),
            ComponentId::EnableAbilitiesTrigger => check_variant(ComponentData::EnableAbilitiesTrigger),
            ComponentId::SphericalGravity => check_variant(ComponentData::SphericalGravity),
            ComponentId::GlobalFogLogic => false,
            ComponentId::CreditsNameOrbLogic => check_variant(ComponentData::CreditsNameOrbLogic),
            ComponentId::DisableLocalCarWarnings => check_variant(ComponentData::DisableLocalCarWarnings),
            ComponentId::CustomName => check_variant(ComponentData::CustomName),
            ComponentId::SplineSegment => check_variant(ComponentData::SplineSegment),
            ComponentId::WarningPulseLight => check_variant(ComponentData::WarningPulseLight),
            ComponentId::RumbleZone => check_variant(ComponentData::RumbleZone),
            ComponentId::HideOnVirusSpiritEvent => check_variant(ComponentData::HideOnVirusSpiritEvent),
            ComponentId::TrackAttachment => check_variant(ComponentData::TrackAttachment),
            ComponentId::LevelPlaylist => check_variant(ComponentData::LevelPlaylist),
            ComponentId::ProfileProgress => check_variant(ComponentData::ProfileProgress),
            ComponentId::GeneralSettings => check_variant(ComponentData::GeneralSettings),
            ComponentId::ReplayAllPurposeTrigger => false,
            ComponentId::WorkshopPublishedFileInfos => check_variant(ComponentData::WorkshopPublishedFileInfos),
            ComponentId::WarpAnchor => check_variant(ComponentData::WarpAnchor),
            ComponentId::SetActiveOnMIDIEvent => check_variant(ComponentData::SetActiveOnMIDIEvent),
            ComponentId::TurnLightOnNearCar => check_variant(ComponentData::TurnLightOnNearCar),
            ComponentId::Traffic => check_variant(ComponentData::Traffic),
            ComponentId::TrackManipulatorNode => check_variant(ComponentData::TrackManipulatorNode),
            ComponentId::TurnLightOnNearCarTrigger => false,
            ComponentId::AudioEventTrigger => check_variant(ComponentData::AudioEventTrigger),
            ComponentId::LevelEditorSettings => check_variant(ComponentData::LevelEditorSettings),
            ComponentId::EmpireProximityDoorLogic => check_variant(ComponentData::EmpireProximityDoorLogic),
            ComponentId::Biodome => check_variant(ComponentData::Biodome),
            ComponentId::TunnelHorrorLogic => check_variant(ComponentData::TunnelHorrorLogic),
            ComponentId::LogicTrigger => false,
            ComponentId::ChangeEmissiveColorLogicTriggerListener => false,
            ComponentId::MoveLogicTriggerListener => false,
            ComponentId::RotateLogicTriggerListener => false,
            ComponentId::ScaleLogicTriggerListener => false,
            ComponentId::VirusSpiritWarpTeaserLogic => check_variant(ComponentData::VirusSpiritWarpTeaserLogic),
            ComponentId::CarReplayData => check_variant(ComponentData::CarReplayData),
            ComponentId::LevelImageCamera => check_variant(ComponentData::LevelImageCamera),
            ComponentId::ParticlesGPU => check_variant(ComponentData::ParticlesGPU),
            ComponentId::KillGridBox => check_variant(ComponentData::KillGridBox),
            ComponentId::GoldenSimples => check_variant(ComponentData::GoldenSimples),
            ComponentId::SetActiveAfterWarp => check_variant(ComponentData::SetActiveAfterWarp),
            ComponentId::AmbientAudioObject => check_variant(ComponentData::AmbientAudioObject),
            ComponentId::BiodomeAudioInterpolator => check_variant(ComponentData::BiodomeAudioInterpolator),
            ComponentId::MoveElectricityAlongWire => check_variant(ComponentData::MoveElectricityAlongWire),
            ComponentId::ActivationRampLogic => check_variant(ComponentData::ActivationRampLogic),
            ComponentId::ZEventTrigger => check_variant(ComponentData::ZEventTrigger),
            ComponentId::ZEventListener => check_variant(ComponentData::ZEventListener),
            ComponentId::BlackPortalLogic => check_variant(ComponentData::BlackPortalLogic),
            ComponentId::VRSettings => check_variant(ComponentData::VRSettings),
            ComponentId::CutsceneCamera => check_variant(ComponentData::CutsceneCamera),
            ComponentId::ProfileStats => check_variant(ComponentData::ProfileStats),
            ComponentId::InterpolateToRotationOnTrigger => check_variant(ComponentData::InterpolateToRotationOnTrigger),
            ComponentId::MoveAlongAttachedTrack => check_variant(ComponentData::MoveAlongAttachedTrack),
            ComponentId::ShowDuringGlitch => check_variant(ComponentData::ShowDuringGlitch),
            ComponentId::AddCameraNoise => check_variant(ComponentData::AddCameraNoise),
            ComponentId::CarVoiceTrigger => check_variant(ComponentData::CarVoiceTrigger),
            ComponentId::HoverScreenSpecialObjectTrigger => check_variant(ComponentData::HoverScreenSpecialObjectTrigger),
            ComponentId::ReplaySettings => check_variant(ComponentData::ReplaySettings),
            ComponentId::CutsceneCamForTrailer => check_variant(ComponentData::CutsceneCamForTrailer),
            ComponentId::LevelInfos => check_variant(ComponentData::LevelInfos),
            ComponentId::AchievementTrigger => check_variant(ComponentData::AchievementTrigger),
            ComponentId::ArenaCarSpawner => check_variant(ComponentData::ArenaCarSpawner),
            ComponentId::Animated => check_variant(ComponentData::Animated),
            ComponentId::BlinkInTrigger => check_variant(ComponentData::BlinkInTrigger),
            ComponentId::CarScreenImageTrigger => check_variant(ComponentData::CarScreenImageTrigger),
            ComponentId::ExcludeFromEMP => check_variant(ComponentData::ExcludeFromEMP),
            ComponentId::InfiniteCooldownTrigger => check_variant(ComponentData::InfiniteCooldownTrigger),
            ComponentId::DiscoverableStuntArea => check_variant(ComponentData::DiscoverableStuntArea),
            ComponentId::ForceVolume => check_variant(ComponentData::ForceVolume),
            ComponentId::AdventureModeCompleteTrigger => check_variant(ComponentData::AdventureModeCompleteTrigger),
            ComponentId::CountdownTextMeshLogic => check_variant(ComponentData::CountdownTextMeshLogic),
            ComponentId::AbilitySignButtonColorLogic => check_variant(ComponentData::AbilitySignButtonColorLogic),
            ComponentId::GoldenAnimator => check_variant(ComponentData::GoldenAnimator),
            ComponentId::StuntCollectibleSpawner => false,
            ComponentId::AnimatorAudio => check_variant(ComponentData::AnimatorAudio),
            ComponentId::AnimatorCameraShake => check_variant(ComponentData::AnimatorCameraShake),
            ComponentId::ShardCluster => check_variant(ComponentData::ShardCluster),
            ComponentId::AdventureSpecialIntro => check_variant(ComponentData::AdventureSpecialIntro),
            ComponentId::AudioEffectZone => check_variant(ComponentData::AudioEffectZone),
            ComponentId::CinematicCamera => check_variant(ComponentData::CinematicCamera),
            ComponentId::CinematicCameraFocalPoint => check_variant(ComponentData::CinematicCameraFocalPoint),
            ComponentId::SetAbilitiesTrigger => check_variant(ComponentData::SetAbilitiesTrigger),
            ComponentId::LostToEchoesIntroCutscene => check_variant(ComponentData::LostToEchoesIntroCutscene),
            ComponentId::CutsceneText => check_variant(ComponentData::CutsceneText),
            ComponentId::UltraPlanet => check_variant(ComponentData::UltraPlanet),
            ComponentId::DeadCarLogic => check_variant(ComponentData::DeadCarLogic),
            ComponentId::RollingBarrelDropperLogic => check_variant(ComponentData::RollingBarrelDropperLogic),
            ComponentId::AdventureFinishTrigger => check_variant(ComponentData::AdventureFinishTrigger),
            ComponentId::AchievementSettings => check_variant(ComponentData::AchievementSettings),
            ComponentId::InterpolateRTPCLogic => check_variant(ComponentData::InterpolateRTPCLogic),
            ComponentId::TriggerCooldownLogic => check_variant(ComponentData::TriggerCooldownLogic),
            ComponentId::ShadowsChangedListener => check_variant(ComponentData::ShadowsChangedListener),
            ComponentId::LookAtCamera => check_variant(ComponentData::LookAtCamera),
            ComponentId::InterceptorCollectable => false,
            ComponentId::CubeMapRenderer => check_variant(ComponentData::CubeMapRenderer),
            ComponentId::RealtimeReflectionRenderer => check_variant(ComponentData::RealtimeReflectionRenderer),
            ComponentId::VirusDropperDroneLogic => check_variant(ComponentData::VirusDropperDroneLogic),
            ComponentId::OnCollisionBreakApartLogic => check_variant(ComponentData::OnCollisionBreakApartLogic),
            ComponentId::CheatSettings => check_variant(ComponentData::CheatSettings),
            ComponentId::IgnoreInCullGroups => check_variant(ComponentData::IgnoreInCullGroups),
            ComponentId::IgnoreInputTrigger => check_variant(ComponentData::IgnoreInputTrigger),
            ComponentId::PowerPosterLogic => check_variant(ComponentData::PowerPosterLogic),
            ComponentId::MusicZone => check_variant(ComponentData::MusicZone),
            ComponentId::LightsFlickerLogic => check_variant(ComponentData::LightsFlickerLogic),
            ComponentId::CutsceneManagerLogic => check_variant(ComponentData::CutsceneManagerLogic),
            ComponentId::FadeOut => check_variant(ComponentData::FadeOut),
            ComponentId::Flock => check_variant(ComponentData::Flock),
            ComponentId::GPSTrigger => check_variant(ComponentData::GPSTrigger),
            ComponentId::ResetOnCarDeath => false,
            ComponentId::SprintMode => check_variant(ComponentData::SprintMode),
            ComponentId::StuntMode => check_variant(ComponentData::StuntMode),
            ComponentId::SoccerMode => check_variant(ComponentData::SoccerMode),
            ComponentId::FreeRoamMode => check_variant(ComponentData::FreeRoamMode),
            ComponentId::ReverseTagMode => check_variant(ComponentData::ReverseTagMode),
            ComponentId::LevelEditorPlayMode => check_variant(ComponentData::LevelEditorPlayMode),
            ComponentId::CoopSprintMode => check_variant(ComponentData::CoopSprintMode),
            ComponentId::ChallengeMode => check_variant(ComponentData::ChallengeMode),
            ComponentId::AdventureMode => check_variant(ComponentData::AdventureMode),
            ComponentId::SpeedAndStyleMode => check_variant(ComponentData::SpeedAndStyleMode),
            ComponentId::TrackmogrifyMode => check_variant(ComponentData::TrackmogrifyMode),
            ComponentId::DemoMode => check_variant(ComponentData::DemoMode),
            ComponentId::MainMenuMode => check_variant(ComponentData::MainMenuMode),
            ComponentId::LostToEchoesMode => check_variant(ComponentData::LostToEchoesMode),
            ComponentId::NexusMode => check_variant(ComponentData::NexusMode),
            ComponentId::TheOtherSideMode => check_variant(ComponentData::TheOtherSideMode),
        }
    }
}

impl Default for ComponentId {
    fn default() -> Self {
        ComponentId::None
    }
}

impl From<ComponentId> for i32 {
    fn from(id: ComponentId) -> Self {
        id.to_i32().unwrap()
    }
}

#[allow(clippy::upper_case_acronyms)]
#[derive(Debug, Clone, PartialEq, PartialOrd, Serialize, Deserialize)]
pub enum ComponentData {
    Transform(Transform),
    MeshRenderer(RawComponentData),
    TextMesh(RawComponentData),
    Light(RawComponentData),
    LensFlare(RawComponentData),
    Projector(RawComponentData),
    SphereCollider(RawComponentData),
    BoxCollider(RawComponentData),
    CapsuleCollider(RawComponentData),
    BezierSplineTrack(RawComponentData),
    TrackSegment(RawComponentData),
    TrackLink(RawComponentData),
    RigidbodyAxisRotationLogic(RawComponentData),
    BackAndForthSawLogic(RawComponentData),
    CheckpointLogic(RawComponentData),
    LightFlickerLogic(RawComponentData),
    Group(RawComponentData),
    TutorialBoxText(RawComponentData),
    FlyingRingLogic(RawComponentData),
    PopupBlockerLogic(RawComponentData),
    PulseLight(RawComponentData),
    PulseMaterial(RawComponentData),
    SmoothRandomPosition(RawComponentData),
    SoccerGoalLogic(RawComponentData),
    VirusMineLogic(RawComponentData),
    BrightenCarHeadlights(RawComponentData),
    GameData(RawComponentData),
    GraphicsSettings(RawComponentData),
    AudioSettings(RawComponentData),
    ControlsSettings(RawComponentData),
    Profile(RawComponentData),
    ToolInputCombos(RawComponentData),
    ColorPreset(RawComponentData),
    LocalLeaderboard(RawComponentData),
    AxisRotationLogic(RawComponentData),
    ParticleEmitLogic(RawComponentData),
    VirusSpiritSpawner(RawComponentData),
    PulseRotateOnTrigger(RawComponentData),
    TeleporterEntrance(RawComponentData),
    TeleporterExit(RawComponentData),
    ControlScheme(RawComponentData),
    DeviceToSchemeLinks(RawComponentData),
    ObjectSpawnCircle(RawComponentData),
    InterpolateToPositionOnTrigger(RawComponentData),
    EngageBrokenPieces(RawComponentData),
    GravityToggle(RawComponentData),
    CarSpawner(RawComponentData),
    RaceStartCarSpawner(RawComponentData),
    LevelEditorCarSpawner(RawComponentData),
    InfoDisplayLogic(RawComponentData),
    MusicTrigger(RawComponentData),
    TabPopulator(RawComponentData),
    AdventureAbilitySettings(RawComponentData),
    IndicatorDisplayLogic(RawComponentData),
    PulseCoreLogic(RawComponentData),
    PulseAll(RawComponentData),
    TeleporterExitCheckpoint(RawComponentData),
    LevelSettings(RawComponentData),
    WingCorruptionZone(RawComponentData),
    GenerateCreditsNames(RawComponentData),
    IntroCutsceneLightFadeIn(RawComponentData),
    QuarantineTrigger(RawComponentData),
    CarScreenTextDecodeTrigger(RawComponentData),
    GlitchFieldLogic(RawComponentData),
    FogSkyboxAmbientChangeTrigger(RawComponentData),
    FinalCountdownLogic(RawComponentData),
    SetActiveOnIntroCutsceneStarted(RawComponentData),
    RaceEndLogic(RawComponentData),
    EnableAbilitiesTrigger(RawComponentData),
    SphericalGravity(RawComponentData),
    CreditsNameOrbLogic(RawComponentData),
    DisableLocalCarWarnings(RawComponentData),
    CustomName(CustomName),
    SplineSegment(RawComponentData),
    WarningPulseLight(RawComponentData),
    RumbleZone(RawComponentData),
    HideOnVirusSpiritEvent(RawComponentData),
    TrackAttachment(RawComponentData),
    LevelPlaylist(RawComponentData),
    ProfileProgress(RawComponentData),
    GeneralSettings(RawComponentData),
    WorkshopPublishedFileInfos(RawComponentData),
    WarpAnchor(RawComponentData),
    SetActiveOnMIDIEvent(RawComponentData),
    TurnLightOnNearCar(RawComponentData),
    Traffic(RawComponentData),
    TrackManipulatorNode(RawComponentData),
    AudioEventTrigger(RawComponentData),
    LevelEditorSettings(RawComponentData),
    EmpireProximityDoorLogic(RawComponentData),
    Biodome(RawComponentData),
    TunnelHorrorLogic(RawComponentData),
    VirusSpiritWarpTeaserLogic(RawComponentData),
    CarReplayData(RawComponentData),
    LevelImageCamera(RawComponentData),
    ParticlesGPU(RawComponentData),
    KillGridBox(RawComponentData),
    GoldenSimples(GoldenSimples),
    SetActiveAfterWarp(RawComponentData),
    AmbientAudioObject(RawComponentData),
    BiodomeAudioInterpolator(RawComponentData),
    MoveElectricityAlongWire(RawComponentData),
    ActivationRampLogic(RawComponentData),
    ZEventTrigger(RawComponentData),
    ZEventListener(RawComponentData),
    BlackPortalLogic(RawComponentData),
    VRSettings(RawComponentData),
    CutsceneCamera(RawComponentData),
    ProfileStats(RawComponentData),
    InterpolateToRotationOnTrigger(RawComponentData),
    MoveAlongAttachedTrack(RawComponentData),
    ShowDuringGlitch(RawComponentData),
    AddCameraNoise(RawComponentData),
    CarVoiceTrigger(RawComponentData),
    HoverScreenSpecialObjectTrigger(RawComponentData),
    ReplaySettings(RawComponentData),
    CutsceneCamForTrailer(RawComponentData),
    LevelInfos(RawComponentData),
    AchievementTrigger(RawComponentData),
    ArenaCarSpawner(RawComponentData),
    Animated(RawComponentData),
    BlinkInTrigger(RawComponentData),
    CarScreenImageTrigger(RawComponentData),
    ExcludeFromEMP(RawComponentData),
    InfiniteCooldownTrigger(RawComponentData),
    DiscoverableStuntArea(RawComponentData),
    ForceVolume(RawComponentData),
    AdventureModeCompleteTrigger(RawComponentData),
    CountdownTextMeshLogic(RawComponentData),
    AbilitySignButtonColorLogic(RawComponentData),
    GoldenAnimator(RawComponentData),
    AnimatorAudio(RawComponentData),
    AnimatorCameraShake(RawComponentData),
    ShardCluster(RawComponentData),
    AdventureSpecialIntro(RawComponentData),
    AudioEffectZone(RawComponentData),
    CinematicCamera(RawComponentData),
    CinematicCameraFocalPoint(RawComponentData),
    SetAbilitiesTrigger(RawComponentData),
    LostToEchoesIntroCutscene(RawComponentData),
    CutsceneText(RawComponentData),
    UltraPlanet(RawComponentData),
    DeadCarLogic(RawComponentData),
    RollingBarrelDropperLogic(RawComponentData),
    AdventureFinishTrigger(RawComponentData),
    AchievementSettings(RawComponentData),
    InterpolateRTPCLogic(RawComponentData),
    TriggerCooldownLogic(RawComponentData),
    ShadowsChangedListener(RawComponentData),
    LookAtCamera(RawComponentData),
    CubeMapRenderer(RawComponentData),
    RealtimeReflectionRenderer(RawComponentData),
    VirusDropperDroneLogic(RawComponentData),
    OnCollisionBreakApartLogic(RawComponentData),
    CheatSettings(RawComponentData),
    IgnoreInCullGroups(RawComponentData),
    IgnoreInputTrigger(RawComponentData),
    PowerPosterLogic(RawComponentData),
    MusicZone(RawComponentData),
    LightsFlickerLogic(RawComponentData),
    CutsceneManagerLogic(RawComponentData),
    FadeOut(RawComponentData),
    Flock(RawComponentData),
    GPSTrigger(RawComponentData),
    SprintMode(RawComponentData),
    StuntMode(RawComponentData),
    SoccerMode(RawComponentData),
    FreeRoamMode(RawComponentData),
    ReverseTagMode(RawComponentData),
    LevelEditorPlayMode(RawComponentData),
    CoopSprintMode(RawComponentData),
    ChallengeMode(RawComponentData),
    AdventureMode(RawComponentData),
    SpeedAndStyleMode(RawComponentData),
    TrackmogrifyMode(RawComponentData),
    DemoMode(RawComponentData),
    MainMenuMode(RawComponentData),
    LostToEchoesMode(RawComponentData),
    NexusMode(RawComponentData),
    TheOtherSideMode(RawComponentData),
}

impl ComponentData {
    #[rustfmt::skip]
    pub fn id(&self) -> ComponentId {
        match self {
            ComponentData::Transform(_) => ComponentId::Transform,
            ComponentData::MeshRenderer(_) => ComponentId::MeshRenderer,
            ComponentData::TextMesh(_) => ComponentId::TextMesh,
            ComponentData::Light(_) => ComponentId::Light,
            ComponentData::LensFlare(_) => ComponentId::LensFlare,
            ComponentData::Projector(_) => ComponentId::Projector,
            ComponentData::SphereCollider(_) => ComponentId::SphereCollider,
            ComponentData::BoxCollider(_) => ComponentId::BoxCollider,
            ComponentData::CapsuleCollider(_) => ComponentId::CapsuleCollider,
            ComponentData::BezierSplineTrack(_) => ComponentId::BezierSplineTrack,
            ComponentData::TrackSegment(_) => ComponentId::TrackSegment,
            ComponentData::TrackLink(_) => ComponentId::TrackLink,
            ComponentData::RigidbodyAxisRotationLogic(_) => ComponentId::RigidbodyAxisRotationLogic,
            ComponentData::BackAndForthSawLogic(_) => ComponentId::BackAndForthSawLogic,
            ComponentData::CheckpointLogic(_) => ComponentId::CheckpointLogic,
            ComponentData::LightFlickerLogic(_) => ComponentId::LightFlickerLogic,
            ComponentData::Group(_) => ComponentId::Group,
            ComponentData::TutorialBoxText(_) => ComponentId::TutorialBoxText,
            ComponentData::FlyingRingLogic(_) => ComponentId::FlyingRingLogic,
            ComponentData::PopupBlockerLogic(_) => ComponentId::PopupBlockerLogic,
            ComponentData::PulseLight(_) => ComponentId::PulseLight,
            ComponentData::PulseMaterial(_) => ComponentId::PulseMaterial,
            ComponentData::SmoothRandomPosition(_) => ComponentId::SmoothRandomPosition,
            ComponentData::SoccerGoalLogic(_) => ComponentId::SoccerGoalLogic,
            ComponentData::VirusMineLogic(_) => ComponentId::VirusMineLogic,
            ComponentData::BrightenCarHeadlights(_) => ComponentId::BrightenCarHeadlights,
            ComponentData::GameData(_) => ComponentId::GameData,
            ComponentData::GraphicsSettings(_) => ComponentId::GraphicsSettings,
            ComponentData::AudioSettings(_) => ComponentId::AudioSettings,
            ComponentData::ControlsSettings(_) => ComponentId::ControlsSettings,
            ComponentData::Profile(_) => ComponentId::Profile,
            ComponentData::ToolInputCombos(_) => ComponentId::ToolInputCombos,
            ComponentData::ColorPreset(_) => ComponentId::ColorPreset,
            ComponentData::LocalLeaderboard(_) => ComponentId::LocalLeaderboard,
            ComponentData::AxisRotationLogic(_) => ComponentId::AxisRotationLogic,
            ComponentData::ParticleEmitLogic(_) => ComponentId::ParticleEmitLogic,
            ComponentData::VirusSpiritSpawner(_) => ComponentId::VirusSpiritSpawner,
            ComponentData::PulseRotateOnTrigger(_) => ComponentId::PulseRotateOnTrigger,
            ComponentData::TeleporterEntrance(_) => ComponentId::TeleporterEntrance,
            ComponentData::TeleporterExit(_) => ComponentId::TeleporterExit,
            ComponentData::ControlScheme(_) => ComponentId::ControlScheme,
            ComponentData::DeviceToSchemeLinks(_) => ComponentId::DeviceToSchemeLinks,
            ComponentData::ObjectSpawnCircle(_) => ComponentId::ObjectSpawnCircle,
            ComponentData::InterpolateToPositionOnTrigger(_) => ComponentId::InterpolateToPositionOnTrigger,
            ComponentData::EngageBrokenPieces(_) => ComponentId::EngageBrokenPieces,
            ComponentData::GravityToggle(_) => ComponentId::GravityToggle,
            ComponentData::CarSpawner(_) => ComponentId::CarSpawner,
            ComponentData::RaceStartCarSpawner(_) => ComponentId::RaceStartCarSpawner,
            ComponentData::LevelEditorCarSpawner(_) => ComponentId::LevelEditorCarSpawner,
            ComponentData::InfoDisplayLogic(_) => ComponentId::InfoDisplayLogic,
            ComponentData::MusicTrigger(_) => ComponentId::MusicTrigger,
            ComponentData::TabPopulator(_) => ComponentId::TabPopulator,
            ComponentData::AdventureAbilitySettings(_) => ComponentId::AdventureAbilitySettings,
            ComponentData::IndicatorDisplayLogic(_) => ComponentId::IndicatorDisplayLogic,
            ComponentData::PulseCoreLogic(_) => ComponentId::PulseCoreLogic,
            ComponentData::PulseAll(_) => ComponentId::PulseAll,
            ComponentData::TeleporterExitCheckpoint(_) => ComponentId::TeleporterExitCheckpoint,
            ComponentData::LevelSettings(_) => ComponentId::LevelSettings,
            ComponentData::WingCorruptionZone(_) => ComponentId::WingCorruptionZone,
            ComponentData::GenerateCreditsNames(_) => ComponentId::GenerateCreditsNames,
            ComponentData::IntroCutsceneLightFadeIn(_) => ComponentId::IntroCutsceneLightFadeIn,
            ComponentData::QuarantineTrigger(_) => ComponentId::QuarantineTrigger,
            ComponentData::CarScreenTextDecodeTrigger(_) => ComponentId::CarScreenTextDecodeTrigger,
            ComponentData::GlitchFieldLogic(_) => ComponentId::GlitchFieldLogic,
            ComponentData::FogSkyboxAmbientChangeTrigger(_) => ComponentId::FogSkyboxAmbientChangeTrigger,
            ComponentData::FinalCountdownLogic(_) => ComponentId::FinalCountdownLogic,
            ComponentData::SetActiveOnIntroCutsceneStarted(_) => ComponentId::SetActiveOnIntroCutsceneStarted,
            ComponentData::RaceEndLogic(_) => ComponentId::RaceEndLogic,
            ComponentData::EnableAbilitiesTrigger(_) => ComponentId::EnableAbilitiesTrigger,
            ComponentData::SphericalGravity(_) => ComponentId::SphericalGravity,
            ComponentData::CreditsNameOrbLogic(_) => ComponentId::CreditsNameOrbLogic,
            ComponentData::DisableLocalCarWarnings(_) => ComponentId::DisableLocalCarWarnings,
            ComponentData::CustomName(_) => ComponentId::CustomName,
            ComponentData::SplineSegment(_) => ComponentId::SplineSegment,
            ComponentData::WarningPulseLight(_) => ComponentId::WarningPulseLight,
            ComponentData::RumbleZone(_) => ComponentId::RumbleZone,
            ComponentData::HideOnVirusSpiritEvent(_) => ComponentId::HideOnVirusSpiritEvent,
            ComponentData::TrackAttachment(_) => ComponentId::TrackAttachment,
            ComponentData::LevelPlaylist(_) => ComponentId::LevelPlaylist,
            ComponentData::ProfileProgress(_) => ComponentId::ProfileProgress,
            ComponentData::GeneralSettings(_) => ComponentId::GeneralSettings,
            ComponentData::WorkshopPublishedFileInfos(_) => ComponentId::WorkshopPublishedFileInfos,
            ComponentData::WarpAnchor(_) => ComponentId::WarpAnchor,
            ComponentData::SetActiveOnMIDIEvent(_) => ComponentId::SetActiveOnMIDIEvent,
            ComponentData::TurnLightOnNearCar(_) => ComponentId::TurnLightOnNearCar,
            ComponentData::Traffic(_) => ComponentId::Traffic,
            ComponentData::TrackManipulatorNode(_) => ComponentId::TrackManipulatorNode,
            ComponentData::AudioEventTrigger(_) => ComponentId::AudioEventTrigger,
            ComponentData::LevelEditorSettings(_) => ComponentId::LevelEditorSettings,
            ComponentData::EmpireProximityDoorLogic(_) => ComponentId::EmpireProximityDoorLogic,
            ComponentData::Biodome(_) => ComponentId::Biodome,
            ComponentData::TunnelHorrorLogic(_) => ComponentId::TunnelHorrorLogic,
            ComponentData::VirusSpiritWarpTeaserLogic(_) => ComponentId::VirusSpiritWarpTeaserLogic,
            ComponentData::CarReplayData(_) => ComponentId::CarReplayData,
            ComponentData::LevelImageCamera(_) => ComponentId::LevelImageCamera,
            ComponentData::ParticlesGPU(_) => ComponentId::ParticlesGPU,
            ComponentData::KillGridBox(_) => ComponentId::KillGridBox,
            ComponentData::GoldenSimples(_) => ComponentId::GoldenSimples,
            ComponentData::SetActiveAfterWarp(_) => ComponentId::SetActiveAfterWarp,
            ComponentData::AmbientAudioObject(_) => ComponentId::AmbientAudioObject,
            ComponentData::BiodomeAudioInterpolator(_) => ComponentId::BiodomeAudioInterpolator,
            ComponentData::MoveElectricityAlongWire(_) => ComponentId::MoveElectricityAlongWire,
            ComponentData::ActivationRampLogic(_) => ComponentId::ActivationRampLogic,
            ComponentData::ZEventTrigger(_) => ComponentId::ZEventTrigger,
            ComponentData::ZEventListener(_) => ComponentId::ZEventListener,
            ComponentData::BlackPortalLogic(_) => ComponentId::BlackPortalLogic,
            ComponentData::VRSettings(_) => ComponentId::VRSettings,
            ComponentData::CutsceneCamera(_) => ComponentId::CutsceneCamera,
            ComponentData::ProfileStats(_) => ComponentId::ProfileStats,
            ComponentData::InterpolateToRotationOnTrigger(_) => ComponentId::InterpolateToRotationOnTrigger,
            ComponentData::MoveAlongAttachedTrack(_) => ComponentId::MoveAlongAttachedTrack,
            ComponentData::ShowDuringGlitch(_) => ComponentId::ShowDuringGlitch,
            ComponentData::AddCameraNoise(_) => ComponentId::AddCameraNoise,
            ComponentData::CarVoiceTrigger(_) => ComponentId::CarVoiceTrigger,
            ComponentData::HoverScreenSpecialObjectTrigger(_) => ComponentId::HoverScreenSpecialObjectTrigger,
            ComponentData::ReplaySettings(_) => ComponentId::ReplaySettings,
            ComponentData::CutsceneCamForTrailer(_) => ComponentId::CutsceneCamForTrailer,
            ComponentData::LevelInfos(_) => ComponentId::LevelInfos,
            ComponentData::AchievementTrigger(_) => ComponentId::AchievementTrigger,
            ComponentData::ArenaCarSpawner(_) => ComponentId::ArenaCarSpawner,
            ComponentData::Animated(_) => ComponentId::Animated,
            ComponentData::BlinkInTrigger(_) => ComponentId::BlinkInTrigger,
            ComponentData::CarScreenImageTrigger(_) => ComponentId::CarScreenImageTrigger,
            ComponentData::ExcludeFromEMP(_) => ComponentId::ExcludeFromEMP,
            ComponentData::InfiniteCooldownTrigger(_) => ComponentId::InfiniteCooldownTrigger,
            ComponentData::DiscoverableStuntArea(_) => ComponentId::DiscoverableStuntArea,
            ComponentData::ForceVolume(_) => ComponentId::ForceVolume,
            ComponentData::AdventureModeCompleteTrigger(_) => ComponentId::AdventureModeCompleteTrigger,
            ComponentData::CountdownTextMeshLogic(_) => ComponentId::CountdownTextMeshLogic,
            ComponentData::AbilitySignButtonColorLogic(_) => ComponentId::AbilitySignButtonColorLogic,
            ComponentData::GoldenAnimator(_) => ComponentId::GoldenAnimator,
            ComponentData::AnimatorAudio(_) => ComponentId::AnimatorAudio,
            ComponentData::AnimatorCameraShake(_) => ComponentId::AnimatorCameraShake,
            ComponentData::ShardCluster(_) => ComponentId::ShardCluster,
            ComponentData::AdventureSpecialIntro(_) => ComponentId::AdventureSpecialIntro,
            ComponentData::AudioEffectZone(_) => ComponentId::AudioEffectZone,
            ComponentData::CinematicCamera(_) => ComponentId::CinematicCamera,
            ComponentData::CinematicCameraFocalPoint(_) => ComponentId::CinematicCameraFocalPoint,
            ComponentData::SetAbilitiesTrigger(_) => ComponentId::SetAbilitiesTrigger,
            ComponentData::LostToEchoesIntroCutscene(_) => ComponentId::LostToEchoesIntroCutscene,
            ComponentData::CutsceneText(_) => ComponentId::CutsceneText,
            ComponentData::UltraPlanet(_) => ComponentId::UltraPlanet,
            ComponentData::DeadCarLogic(_) => ComponentId::DeadCarLogic,
            ComponentData::RollingBarrelDropperLogic(_) => ComponentId::RollingBarrelDropperLogic,
            ComponentData::AdventureFinishTrigger(_) => ComponentId::AdventureFinishTrigger,
            ComponentData::AchievementSettings(_) => ComponentId::AchievementSettings,
            ComponentData::InterpolateRTPCLogic(_) => ComponentId::InterpolateRTPCLogic,
            ComponentData::TriggerCooldownLogic(_) => ComponentId::TriggerCooldownLogic,
            ComponentData::ShadowsChangedListener(_) => ComponentId::ShadowsChangedListener,
            ComponentData::LookAtCamera(_) => ComponentId::LookAtCamera,
            ComponentData::CubeMapRenderer(_) => ComponentId::CubeMapRenderer,
            ComponentData::RealtimeReflectionRenderer(_) => ComponentId::RealtimeReflectionRenderer,
            ComponentData::VirusDropperDroneLogic(_) => ComponentId::VirusDropperDroneLogic,
            ComponentData::OnCollisionBreakApartLogic(_) => ComponentId::OnCollisionBreakApartLogic,
            ComponentData::CheatSettings(_) => ComponentId::CheatSettings,
            ComponentData::IgnoreInCullGroups(_) => ComponentId::IgnoreInCullGroups,
            ComponentData::IgnoreInputTrigger(_) => ComponentId::IgnoreInputTrigger,
            ComponentData::PowerPosterLogic(_) => ComponentId::PowerPosterLogic,
            ComponentData::MusicZone(_) => ComponentId::MusicZone,
            ComponentData::LightsFlickerLogic(_) => ComponentId::LightsFlickerLogic,
            ComponentData::CutsceneManagerLogic(_) => ComponentId::CutsceneManagerLogic,
            ComponentData::FadeOut(_) => ComponentId::FadeOut,
            ComponentData::Flock(_) => ComponentId::Flock,
            ComponentData::GPSTrigger(_) => ComponentId::GPSTrigger,
            ComponentData::SprintMode(_) => ComponentId::SprintMode,
            ComponentData::StuntMode(_) => ComponentId::StuntMode,
            ComponentData::SoccerMode(_) => ComponentId::SoccerMode,
            ComponentData::FreeRoamMode(_) => ComponentId::FreeRoamMode,
            ComponentData::ReverseTagMode(_) => ComponentId::ReverseTagMode,
            ComponentData::LevelEditorPlayMode(_) => ComponentId::LevelEditorPlayMode,
            ComponentData::CoopSprintMode(_) => ComponentId::CoopSprintMode,
            ComponentData::ChallengeMode(_) => ComponentId::ChallengeMode,
            ComponentData::AdventureMode(_) => ComponentId::AdventureMode,
            ComponentData::SpeedAndStyleMode(_) => ComponentId::SpeedAndStyleMode,
            ComponentData::TrackmogrifyMode(_) => ComponentId::TrackmogrifyMode,
            ComponentData::DemoMode(_) => ComponentId::DemoMode,
            ComponentData::MainMenuMode(_) => ComponentId::MainMenuMode,
            ComponentData::LostToEchoesMode(_) => ComponentId::LostToEchoesMode,
            ComponentData::NexusMode(_) => ComponentId::NexusMode,
            ComponentData::TheOtherSideMode(_) => ComponentId::TheOtherSideMode,
        }
    }

    pub(crate) fn dispatch<D: ComponentDataDispatch>(
        &mut self,
        mut dispatcher: D,
    ) -> Result<(), Error> {
        match self {
            ComponentData::Transform(data) => dispatcher.implemented(data),
            ComponentData::GoldenSimples(data) => dispatcher.implemented(data),
            ComponentData::MeshRenderer(data) => dispatcher.raw(data),
            ComponentData::TextMesh(data) => dispatcher.raw(data),
            ComponentData::Light(data) => dispatcher.raw(data),
            ComponentData::LensFlare(data) => dispatcher.raw(data),
            ComponentData::Projector(data) => dispatcher.raw(data),
            ComponentData::SphereCollider(data) => dispatcher.raw(data),
            ComponentData::BoxCollider(data) => dispatcher.raw(data),
            ComponentData::CapsuleCollider(data) => dispatcher.raw(data),
            ComponentData::BezierSplineTrack(data) => dispatcher.raw(data),
            ComponentData::TrackSegment(data) => dispatcher.raw(data),
            ComponentData::TrackLink(data) => dispatcher.raw(data),
            ComponentData::RigidbodyAxisRotationLogic(data) => dispatcher.raw(data),
            ComponentData::BackAndForthSawLogic(data) => dispatcher.raw(data),
            ComponentData::CheckpointLogic(data) => dispatcher.raw(data),
            ComponentData::LightFlickerLogic(data) => dispatcher.raw(data),
            ComponentData::Group(data) => dispatcher.raw(data),
            ComponentData::TutorialBoxText(data) => dispatcher.raw(data),
            ComponentData::FlyingRingLogic(data) => dispatcher.raw(data),
            ComponentData::PopupBlockerLogic(data) => dispatcher.raw(data),
            ComponentData::PulseLight(data) => dispatcher.raw(data),
            ComponentData::PulseMaterial(data) => dispatcher.raw(data),
            ComponentData::SmoothRandomPosition(data) => dispatcher.raw(data),
            ComponentData::SoccerGoalLogic(data) => dispatcher.raw(data),
            ComponentData::VirusMineLogic(data) => dispatcher.raw(data),
            ComponentData::BrightenCarHeadlights(data) => dispatcher.raw(data),
            ComponentData::GameData(data) => dispatcher.raw(data),
            ComponentData::GraphicsSettings(data) => dispatcher.raw(data),
            ComponentData::AudioSettings(data) => dispatcher.raw(data),
            ComponentData::ControlsSettings(data) => dispatcher.raw(data),
            ComponentData::Profile(data) => dispatcher.raw(data),
            ComponentData::ToolInputCombos(data) => dispatcher.raw(data),
            ComponentData::ColorPreset(data) => dispatcher.raw(data),
            ComponentData::LocalLeaderboard(data) => dispatcher.raw(data),
            ComponentData::AxisRotationLogic(data) => dispatcher.raw(data),
            ComponentData::ParticleEmitLogic(data) => dispatcher.raw(data),
            ComponentData::VirusSpiritSpawner(data) => dispatcher.raw(data),
            ComponentData::PulseRotateOnTrigger(data) => dispatcher.raw(data),
            ComponentData::TeleporterEntrance(data) => dispatcher.raw(data),
            ComponentData::TeleporterExit(data) => dispatcher.raw(data),
            ComponentData::ControlScheme(data) => dispatcher.raw(data),
            ComponentData::DeviceToSchemeLinks(data) => dispatcher.raw(data),
            ComponentData::ObjectSpawnCircle(data) => dispatcher.raw(data),
            ComponentData::InterpolateToPositionOnTrigger(data) => dispatcher.raw(data),
            ComponentData::EngageBrokenPieces(data) => dispatcher.raw(data),
            ComponentData::GravityToggle(data) => dispatcher.raw(data),
            ComponentData::CarSpawner(data) => dispatcher.raw(data),
            ComponentData::RaceStartCarSpawner(data) => dispatcher.raw(data),
            ComponentData::LevelEditorCarSpawner(data) => dispatcher.raw(data),
            ComponentData::InfoDisplayLogic(data) => dispatcher.raw(data),
            ComponentData::MusicTrigger(data) => dispatcher.raw(data),
            ComponentData::TabPopulator(data) => dispatcher.raw(data),
            ComponentData::AdventureAbilitySettings(data) => dispatcher.raw(data),
            ComponentData::IndicatorDisplayLogic(data) => dispatcher.raw(data),
            ComponentData::PulseCoreLogic(data) => dispatcher.raw(data),
            ComponentData::PulseAll(data) => dispatcher.raw(data),
            ComponentData::TeleporterExitCheckpoint(data) => dispatcher.raw(data),
            ComponentData::LevelSettings(data) => dispatcher.raw(data),
            ComponentData::WingCorruptionZone(data) => dispatcher.raw(data),
            ComponentData::GenerateCreditsNames(data) => dispatcher.raw(data),
            ComponentData::IntroCutsceneLightFadeIn(data) => dispatcher.raw(data),
            ComponentData::QuarantineTrigger(data) => dispatcher.raw(data),
            ComponentData::CarScreenTextDecodeTrigger(data) => dispatcher.raw(data),
            ComponentData::GlitchFieldLogic(data) => dispatcher.raw(data),
            ComponentData::FogSkyboxAmbientChangeTrigger(data) => dispatcher.raw(data),
            ComponentData::FinalCountdownLogic(data) => dispatcher.raw(data),
            ComponentData::SetActiveOnIntroCutsceneStarted(data) => dispatcher.raw(data),
            ComponentData::RaceEndLogic(data) => dispatcher.raw(data),
            ComponentData::EnableAbilitiesTrigger(data) => dispatcher.raw(data),
            ComponentData::SphericalGravity(data) => dispatcher.raw(data),
            ComponentData::CreditsNameOrbLogic(data) => dispatcher.raw(data),
            ComponentData::DisableLocalCarWarnings(data) => dispatcher.raw(data),
            ComponentData::CustomName(data) => dispatcher.implemented(data),
            ComponentData::SplineSegment(data) => dispatcher.raw(data),
            ComponentData::WarningPulseLight(data) => dispatcher.raw(data),
            ComponentData::RumbleZone(data) => dispatcher.raw(data),
            ComponentData::HideOnVirusSpiritEvent(data) => dispatcher.raw(data),
            ComponentData::TrackAttachment(data) => dispatcher.raw(data),
            ComponentData::LevelPlaylist(data) => dispatcher.raw(data),
            ComponentData::ProfileProgress(data) => dispatcher.raw(data),
            ComponentData::GeneralSettings(data) => dispatcher.raw(data),
            ComponentData::WorkshopPublishedFileInfos(data) => dispatcher.raw(data),
            ComponentData::WarpAnchor(data) => dispatcher.raw(data),
            ComponentData::SetActiveOnMIDIEvent(data) => dispatcher.raw(data),
            ComponentData::TurnLightOnNearCar(data) => dispatcher.raw(data),
            ComponentData::Traffic(data) => dispatcher.raw(data),
            ComponentData::TrackManipulatorNode(data) => dispatcher.raw(data),
            ComponentData::AudioEventTrigger(data) => dispatcher.raw(data),
            ComponentData::LevelEditorSettings(data) => dispatcher.raw(data),
            ComponentData::EmpireProximityDoorLogic(data) => dispatcher.raw(data),
            ComponentData::Biodome(data) => dispatcher.raw(data),
            ComponentData::TunnelHorrorLogic(data) => dispatcher.raw(data),
            ComponentData::VirusSpiritWarpTeaserLogic(data) => dispatcher.raw(data),
            ComponentData::CarReplayData(data) => dispatcher.raw(data),
            ComponentData::LevelImageCamera(data) => dispatcher.raw(data),
            ComponentData::ParticlesGPU(data) => dispatcher.raw(data),
            ComponentData::KillGridBox(data) => dispatcher.raw(data),
            ComponentData::SetActiveAfterWarp(data) => dispatcher.raw(data),
            ComponentData::AmbientAudioObject(data) => dispatcher.raw(data),
            ComponentData::BiodomeAudioInterpolator(data) => dispatcher.raw(data),
            ComponentData::MoveElectricityAlongWire(data) => dispatcher.raw(data),
            ComponentData::ActivationRampLogic(data) => dispatcher.raw(data),
            ComponentData::ZEventTrigger(data) => dispatcher.raw(data),
            ComponentData::ZEventListener(data) => dispatcher.raw(data),
            ComponentData::BlackPortalLogic(data) => dispatcher.raw(data),
            ComponentData::VRSettings(data) => dispatcher.raw(data),
            ComponentData::CutsceneCamera(data) => dispatcher.raw(data),
            ComponentData::ProfileStats(data) => dispatcher.raw(data),
            ComponentData::InterpolateToRotationOnTrigger(data) => dispatcher.raw(data),
            ComponentData::MoveAlongAttachedTrack(data) => dispatcher.raw(data),
            ComponentData::ShowDuringGlitch(data) => dispatcher.raw(data),
            ComponentData::AddCameraNoise(data) => dispatcher.raw(data),
            ComponentData::CarVoiceTrigger(data) => dispatcher.raw(data),
            ComponentData::HoverScreenSpecialObjectTrigger(data) => dispatcher.raw(data),
            ComponentData::ReplaySettings(data) => dispatcher.raw(data),
            ComponentData::CutsceneCamForTrailer(data) => dispatcher.raw(data),
            ComponentData::LevelInfos(data) => dispatcher.raw(data),
            ComponentData::AchievementTrigger(data) => dispatcher.raw(data),
            ComponentData::ArenaCarSpawner(data) => dispatcher.raw(data),
            ComponentData::Animated(data) => dispatcher.raw(data),
            ComponentData::BlinkInTrigger(data) => dispatcher.raw(data),
            ComponentData::CarScreenImageTrigger(data) => dispatcher.raw(data),
            ComponentData::ExcludeFromEMP(data) => dispatcher.raw(data),
            ComponentData::InfiniteCooldownTrigger(data) => dispatcher.raw(data),
            ComponentData::DiscoverableStuntArea(data) => dispatcher.raw(data),
            ComponentData::ForceVolume(data) => dispatcher.raw(data),
            ComponentData::AdventureModeCompleteTrigger(data) => dispatcher.raw(data),
            ComponentData::CountdownTextMeshLogic(data) => dispatcher.raw(data),
            ComponentData::AbilitySignButtonColorLogic(data) => dispatcher.raw(data),
            ComponentData::GoldenAnimator(data) => dispatcher.raw(data),
            ComponentData::AnimatorAudio(data) => dispatcher.raw(data),
            ComponentData::AnimatorCameraShake(data) => dispatcher.raw(data),
            ComponentData::ShardCluster(data) => dispatcher.raw(data),
            ComponentData::AdventureSpecialIntro(data) => dispatcher.raw(data),
            ComponentData::AudioEffectZone(data) => dispatcher.raw(data),
            ComponentData::CinematicCamera(data) => dispatcher.raw(data),
            ComponentData::CinematicCameraFocalPoint(data) => dispatcher.raw(data),
            ComponentData::SetAbilitiesTrigger(data) => dispatcher.raw(data),
            ComponentData::LostToEchoesIntroCutscene(data) => dispatcher.raw(data),
            ComponentData::CutsceneText(data) => dispatcher.raw(data),
            ComponentData::UltraPlanet(data) => dispatcher.raw(data),
            ComponentData::DeadCarLogic(data) => dispatcher.raw(data),
            ComponentData::RollingBarrelDropperLogic(data) => dispatcher.raw(data),
            ComponentData::AdventureFinishTrigger(data) => dispatcher.raw(data),
            ComponentData::AchievementSettings(data) => dispatcher.raw(data),
            ComponentData::InterpolateRTPCLogic(data) => dispatcher.raw(data),
            ComponentData::TriggerCooldownLogic(data) => dispatcher.raw(data),
            ComponentData::ShadowsChangedListener(data) => dispatcher.raw(data),
            ComponentData::LookAtCamera(data) => dispatcher.raw(data),
            ComponentData::CubeMapRenderer(data) => dispatcher.raw(data),
            ComponentData::RealtimeReflectionRenderer(data) => dispatcher.raw(data),
            ComponentData::VirusDropperDroneLogic(data) => dispatcher.raw(data),
            ComponentData::OnCollisionBreakApartLogic(data) => dispatcher.raw(data),
            ComponentData::CheatSettings(data) => dispatcher.raw(data),
            ComponentData::IgnoreInCullGroups(data) => dispatcher.raw(data),
            ComponentData::IgnoreInputTrigger(data) => dispatcher.raw(data),
            ComponentData::PowerPosterLogic(data) => dispatcher.raw(data),
            ComponentData::MusicZone(data) => dispatcher.raw(data),
            ComponentData::LightsFlickerLogic(data) => dispatcher.raw(data),
            ComponentData::CutsceneManagerLogic(data) => dispatcher.raw(data),
            ComponentData::FadeOut(data) => dispatcher.raw(data),
            ComponentData::Flock(data) => dispatcher.raw(data),
            ComponentData::GPSTrigger(data) => dispatcher.raw(data),
            ComponentData::SprintMode(data) => dispatcher.raw(data),
            ComponentData::StuntMode(data) => dispatcher.raw(data),
            ComponentData::SoccerMode(data) => dispatcher.raw(data),
            ComponentData::FreeRoamMode(data) => dispatcher.raw(data),
            ComponentData::ReverseTagMode(data) => dispatcher.raw(data),
            ComponentData::LevelEditorPlayMode(data) => dispatcher.raw(data),
            ComponentData::CoopSprintMode(data) => dispatcher.raw(data),
            ComponentData::ChallengeMode(data) => dispatcher.raw(data),
            ComponentData::AdventureMode(data) => dispatcher.raw(data),
            ComponentData::SpeedAndStyleMode(data) => dispatcher.raw(data),
            ComponentData::TrackmogrifyMode(data) => dispatcher.raw(data),
            ComponentData::DemoMode(data) => dispatcher.raw(data),
            ComponentData::MainMenuMode(data) => dispatcher.raw(data),
            ComponentData::LostToEchoesMode(data) => dispatcher.raw(data),
            ComponentData::NexusMode(data) => dispatcher.raw(data),
            ComponentData::TheOtherSideMode(data) => dispatcher.raw(data),
        }
    }
}

/// Raw, binary component data as stored in the bytes format.
#[derive(Debug, Clone, Default, Hash, Eq, PartialEq, Ord, PartialOrd, Serialize, Deserialize)]
pub struct RawComponentData(pub Vec<u8>);

pub(crate) trait ComponentDataDispatch {
    fn implemented<T: Serializable>(&mut self, data: &mut T) -> Result<(), Error>;
    fn raw(&mut self, data: &RawComponentData) -> Result<(), Error>;
}

pub(crate) trait ComponentBuilder {
    fn implemented<T: Serializable>(
        &mut self,
        component_data_constructor: fn(T) -> ComponentData,
        implemented_version: i32,
    ) -> Result<Component, Error>;
    fn raw(
        &mut self,
        component_data_constructor: fn(RawComponentData) -> ComponentData,
    ) -> Result<Component, Error>;
}
