name: Merge dev branch

on:
  push:
    branches:
      - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for checks
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: dev
          running-workflow-name: pull-request
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      # Workaround for permissions issue when running the following job
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fast Forward Merge
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          branchtomerge: dev
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
