name: Merge dev branch

on:
  push:
    branches:
      - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Open Pull Request
        uses: repo-sync/pull-request@v2
        id: open-pr
        with:
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v1
        if: ${{ steps.open-pr.outputs.pr_number != null }}
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: rebase