on:
  push:
    branches:
      - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: rebase
